## ---------------------------------------------------------------------------
## Licensed to the Apache Software Foundation (ASF) under one or more
## contributor license agreements.  See the NOTICE file distributed with
## this work for additional information regarding copyright ownership.
## The ASF licenses this file to You under the Apache License, Version 2.0
## (the "License"); you may not use this file except in compliance with
## the License.  You may obtain a copy of the License at
##
##      http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
## ---------------------------------------------------------------------------

version: '2.1'

services:
  service-center:
    image: "servicecomb/service-center"
    hostname: service-center
    ports:
      - "30100:30100"

  postgres:
    image: "postgres"
    hostname: postgres
    environment:
      - POSTGRES_DB=saga
      - POSTGRES_USER=saga
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    healthcheck:
        test: ["CMD-SHELL", "nc -z localhost 5432 &> /dev/null; echo $$?"]
        interval: 30s
        timeout: 10s
        retries: 5

  car-rental-service:
    image: "car-rental-service:0.3.0-SNAPSHOT"
    hostname: car
    links:
      - "service-center:sc.servicecomb.io"
    ports:
      - "8080"

  flight-booking-service:
    image: "flight-booking-service:0.3.0-SNAPSHOT"
    hostname: flight
    links:
      - "service-center:sc.servicecomb.io"
    ports:
      - "8080"

  hotel-reservation-service:
    image: "hotel-reservation-service:0.3.0-SNAPSHOT"
    hostname: hotel
    links:
      - "service-center:sc.servicecomb.io"
    ports:
      - "8080"

  payment-service:
    image: "payment-service:0.3.0-SNAPSHOT"
    hostname: payment
    links:
      - "service-center:sc.servicecomb.io"
    ports:
      - "8080"

  saga:
    image: "saga-spring:0.3.0-SNAPSHOT"
    hostname: saga
    links:
      - "postgres:postgres.servicecomb.io"
      - "service-center:sc.servicecomb.io"
      - "car-rental-service:car.servicecomb.io"
      - "flight-booking-service:flight.servicecomb.io"
      - "hotel-reservation-service:hotel.servicecomb.io"
      - "payment-service:payment.servicecomb.io"
    environment:
      - JAVA_OPTS=-Dspring.profiles.active=prd,servicecomb -Dcse.service.registry.address=http://sc.servicecomb.io:30100
    ports:
      - "8083:8080"
    depends_on:
      postgres:
        condition: service_healthy

  web:
    image: "saga-web:0.3.0-SNAPSHOT"
    hostname: web
    links:
      - "service-center:sc.servicecomb.io"
      - "saga:saga.servicecomb.io"
    environment:
      - JAVA_OPTS=-Dspring.profiles.active=prd,servicecomb -Dcse.service.registry.address=http://sc.servicecomb.io:30100
    ports:
      - "8888:8888"
