sudo: required

language: java

jdk:
  - oraclejdk8

script:
  - mvn clean install -Pjacoco coveralls:report

after_success:
  - mvn clean test -f saga-demo -Pdemo
  - mvn deploy -DskipTests --settings .travis.settings.xml

env:
  global:
    - secure: "agG8Yu9+2dNU0njxnupfORjYb3WABuJxumiHD0TEQDf2inb+uImuher22wGKq5fxkTIlPB1DobByuDMRtLknW+gBKFddiSgK6ymeX/vu7ukmgU6hPApy4UgMhHmSKR0wgR/vdLuysvNRXhyOcP7fFKu5I6ELu7jNiZNLVzC60N3jxUhqghX+m4W9Rig2kbEgi6ZyWw3MemHj2TtpXhBhYKXRyJddIGz0PiX3ZYXWU0erRN1w6CUC0NrvUiIs/ZMSWwR+SBLaGx4th6Lwov8+ZoPwmV2r9tAgZHgzMM5nAjNQBsUlpH07fjo0GSW9RTgoUX65nQJqwsUeLF9fq7KJxTS/5YsQJEY/TUP/NLAHJe0p8HhAHwh6t03GV4l+Jd4h7DmKklSJqv+4SkVKt8ACQvt450+PUQGF0MdkaOhVMzpWlfiSZSaeU0HM/kiZe6T0e6ZGcrBL/NrLDHlCpyc5eaheSYU3rnnU4f+QK3MmvckLXy8+DSZlWVBXJ759SlBjUWcpqEEt/XRJZCBEmpGOs5A6BNuRAU8A7c9Go92Tqs93rbxKgvAMkXK2P9H0kKs4Pxkc+lrTnihhuw8HEnDH5TsvtVibknH1jrwPp5w4Br59WWZ6rR5HKz9r9VUeWDfEGUiMdihAXRd7urLCc3JwsC0BwNzDGGAiDM1OdbyEALM="
    - secure: "MaLfZIH/DNWriiAWn0mGbbYN6D0iy4t+W6NQNAFDdzgkGcByrPOtZ+Gf2axrpjM184n0CHtnBFD9RLaK0fBnXYz3+vcbM4lsE0XkxjKkZZaBgJ86cwqt1t31Kmevn33m/oFck914I2VlzDFszL4ok/WFlj5/X7Xr0YEUxSrW7exRHRw28jB+j85JqzREA2LGGJD4samT1STPqFQmFg9d45PKonx9hboPc5peNSbJFM1HCHMG9HWLS8vEKWXqmPh7/3NyjHtUBl05bbC8xx5X3tTDB6cq5i5EdflaVNO5nAHxoT+FxX/GnjmXVHx7uPv6LClayKpViY+HlmoFbBZ0F8bVi43+Yjal2NacgJDNEf5IM1QtuymMgiepAGWJ5l1prXSGNosjLLQNWvxfc04aa2j3t+aPIlYEE7aQ1NMqRceCnKMOJeFln1J5vIx6iW83Db57wZJPowKRgmMUgwiH5sYRO5MIfsz8s1Y79xuSWYoBbb0rRrKkw4Bph6Dc5TOKeSby4OKI0j2ao0nRRFgcdxdyfcWyNjUQ/zo1PnlybZ+fuw0E1+EU5pr6iOYZT0O7GebJQ7Qg9uX81UssBOpj9kUJIikl/v/hWLzQ/xIpBQtkJtuCwXAfIZZuphnMPtBpDqwdgcZMHAyNdkIQPJG2IaHW25qQXySyL7keMxLUuZ0="
